import type { CachedSource } from '@/discovery/maintenance/msource/run';

import { MSOURCE_CATALOG } from './catalogData';

/**
 * Class-level M-SOURCE results published by the worker host (generated by
 * tools/build-msource-catalog.mjs from docs/maintenance/data/msource/*-catalog.json). Keyed by
 * vehicle CLASS; structured evidence and provenance only — no document bytes.
 *
 * Class keys are kind|make|model|year|cc|engine codes|fuel|transmission. The V1 matcher never
 * uses the transmission, so an entry also serves a vehicle whose transmission is UNKNOWN (the
 * registry flow does not record it). Every other segment must be identical.
 */
const TRANSMISSION = 7;

function compatible(entryKey: string, vehicleKey: string): boolean {
  if (entryKey === vehicleKey) return true;
  const a = entryKey.split('|');
  const b = vehicleKey.split('|');
  if (a.length !== b.length || b[TRANSMISSION] !== '') return false;
  return a.every((x, i) => i === TRANSMISSION || x === b[i]);
}

export function catalogFor(classKey: string): { canonicalUrl: string; value: CachedSource }[] {
  const entry =
    MSOURCE_CATALOG.find((c) => c.classKey === classKey) ??
    MSOURCE_CATALOG.find((c) => compatible(c.classKey, classKey));
  return (entry?.sources ?? []) as { canonicalUrl: string; value: CachedSource }[];
}
