import { readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * The on-device reader page (assets/ocr/ocr-reader.html, generated by
 * tools/build-ocr-webview.mjs) must parse: a syntax error there stops every photo / scan reading
 * (2026-10-07: an unescaped line break inside a string broke both camera and file import).
 */
describe('photo reader page', () => {
  const html = readFileSync(join(__dirname, '../../../../../assets/ocr/ocr-reader.html'), 'utf8');
  const script = html.slice(
    html.indexOf('<script>') + '<script>'.length,
    html.lastIndexOf('</script>'),
  );

  it('its script parses', () => {
    expect(() => new Function(script)).not.toThrow();
  });

  it('reads text and, in "table" mode, the maintenance table', () => {
    expect(script).toContain('window.__akChunk = function (id, b64, last, mode)');
    expect(script).toContain("mode === 'table'");
    expect(script).toContain('function readServiceTable(img, ocr)');
  });
});
