import { createClient } from '@supabase/supabase-js';

import { adminClient, localStatus, stagingTarget } from '../testing/localStack';

/**
 * P2B: sign-in on the HOSTED staging project (skipped locally). Delivery of the code by e-mail is
 * not exercised: on the Free plan the built-in sender only reaches the organization's team
 * members and templates cannot be changed (documented limitation, P2C blocker). What IS verified
 * here is everything else of the flow the app uses: a 6-digit one-time code (generated by the
 * admin API instead of being read from an inbox) verified with verifyOtp({ type: 'email' }),
 * sessions, refresh, device-only sign-out, and that the code is single-use.
 */

const maybe = stagingTarget() ? describe : describe.skip;

function client() {
  const s = localStatus();
  return createClient(s.API_URL, s.ANON_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

async function codeFor(email: string): Promise<string> {
  const { data, error } = await adminClient().auth.admin.generateLink({ type: 'magiclink', email });
  if (error) throw error;
  return data.properties.email_otp;
}

maybe('hosted staging sign-in (P2B)', () => {
  const email = `p2b-auth-${Date.now()}@autokeep.test`;
  let userId: string | null = null;

  afterAll(async () => {
    if (userId) await adminClient().auth.admin.deleteUser(userId);
  });

  it('the one-time code is 6 digits and signs the user in exactly once', async () => {
    const created = await adminClient().auth.admin.createUser({ email, email_confirm: true });
    userId = created.data.user!.id;
    const code = await codeFor(email);
    expect(code).toMatch(/^\d{6}$/);

    const device = client();
    const r = await device.auth.verifyOtp({ email, token: code, type: 'email' });
    expect(r.error).toBeNull();
    expect(r.data.session?.user.email).toBe(email);

    // Single use.
    const again = await client().auth.verifyOtp({ email, token: code, type: 'email' });
    expect(again.error).not.toBeNull();
    // A wrong code is refused.
    const wrong = await client().auth.verifyOtp({ email, token: '000000', type: 'email' });
    expect(wrong.error).not.toBeNull();
  });

  it('sessions refresh, and signing out one device leaves the other signed in', async () => {
    const a = client();
    const b = client();
    await a.auth.verifyOtp({ email, token: await codeFor(email), type: 'email' });
    await b.auth.verifyOtp({ email, token: await codeFor(email), type: 'email' });

    const before = (await a.auth.getSession()).data.session!;
    const refreshed = await a.auth.refreshSession();
    expect(refreshed.error).toBeNull();
    expect(refreshed.data.session!.access_token).not.toBe(before.access_token);

    await a.auth.signOut({ scope: 'local' });
    expect((await a.auth.getSession()).data.session).toBeNull();
    const stillB = await b.auth.getUser();
    expect(stillB.data.user?.email).toBe(email);
  });

  it('Free-plan limitation: the built-in sender refuses an address outside the team', async () => {
    const outsider = `p2b-outsider-${Date.now()}@autokeep.test`;
    const r = await client().auth.signInWithOtp({
      email: outsider,
      options: { shouldCreateUser: true },
    });
    // Recorded, not asserted as a product behaviour: the exact outcome is the platform's.
    // eslint-disable-next-line no-console
    console.log('P2B built-in e-mail to a non-team address:', r.error?.status, r.error?.message);
    const { data } = await adminClient().auth.admin.listUsers({ perPage: 1000 });
    const leaked = data.users.find((u) => u.email === outsider);
    if (leaked) await adminClient().auth.admin.deleteUser(leaked.id);
  });
});
